# Generated by Django 5.2 on 2025-04-28 22:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Disciplina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=10, unique=True, verbose_name='Código da Disciplina')),
                ('nome', models.CharField(max_length=50, verbose_name='Nome')),
                ('descricao', models.TextField(verbose_name='Descrição')),
                ('carga_horaria', models.IntegerField(verbose_name='Carga Horária')),
                ('creditos', models.IntegerField(verbose_name='Créditos')),
            ],
        ),
        migrations.CreateModel(
            name='Estudante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricula', models.CharField(max_length=50, unique=True, verbose_name='Matrícula')),
                ('primeiro_nome', models.CharField(max_length=50, verbose_name='Primeiro Nome')),
                ('sobrenome', models.CharField(max_length=50, verbose_name='Sobrenome')),
                ('posto_graduacao', models.CharField(max_length=50, verbose_name='Posto ou Graduação')),
                ('nome_guerra', models.CharField(max_length=50, verbose_name='Nome de Guerra')),
                ('data_de_aniversario', models.DateField(verbose_name='Data de Aniversário')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='E-mail')),
            ],
        ),
        migrations.CreateModel(
            name='Escore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('escore', models.DecimalField(decimal_places=2, max_digits=5)),
                ('data_do_registro', models.DateField(auto_now_add=True)),
                ('disciplina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.disciplina')),
                ('estudante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.estudante')),
            ],
        ),
        migrations.CreateModel(
            name='Inscricao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_inscricao', models.DateField(auto_now_add=True, verbose_name='Data de Inscrição')),
                ('disciplina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.disciplina')),
                ('estudante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.estudante')),
            ],
        ),
        migrations.CreateModel(
            name='Instrutor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricula', models.CharField(max_length=50, unique=True, verbose_name='Matrícula')),
                ('primeiro_nome', models.CharField(max_length=50, verbose_name='Primeiro Nome')),
                ('sobrenome', models.CharField(max_length=50, verbose_name='Último Nome')),
                ('posto_graduacao', models.CharField(max_length=50, verbose_name='Posto ou Graduação')),
                ('nome_guerra', models.CharField(max_length=50, verbose_name='Nome de Guerra')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='E-mail')),
                ('disciplina', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.disciplina')),
            ],
        ),
        migrations.CreateModel(
            name='Monitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricula', models.CharField(max_length=50, unique=True, verbose_name='Matrícula')),
                ('primeiro_nome', models.CharField(max_length=50, verbose_name='Primeiro Nome')),
                ('sobrenome', models.CharField(max_length=50, verbose_name='Último Nome')),
                ('posto_graduacao', models.CharField(max_length=50, verbose_name='Posto ou Graduação')),
                ('nome_guerra', models.CharField(max_length=50, verbose_name='Nome de Guerra')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='E-mail')),
                ('disciplina', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.disciplina')),
            ],
        ),
        migrations.CreateModel(
            name='Presenca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('status', models.CharField(choices=[('Presente', 'Presente'), ('Ausente', 'Ausente')], max_length=10)),
                ('estudante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.estudante')),
            ],
        ),
    ]
