# Generated by Django 5.2 on 2025-05-18 19:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Disciplina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=10, unique=True, verbose_name='Código da Disciplina')),
                ('nome', models.CharField(max_length=30, verbose_name='Nome')),
                ('descricao', models.TextField(verbose_name='Descrição')),
                ('carga_horaria', models.IntegerField(verbose_name='Carga Horária')),
                ('creditos', models.IntegerField(verbose_name='Créditos')),
            ],
        ),
        migrations.CreateModel(
            name='Estudante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricula', models.CharField(max_length=10, unique=True, verbose_name='Matrícula')),
                ('primeiro_nome', models.CharField(max_length=30, verbose_name='Primeiro Nome')),
                ('sobrenome', models.CharField(max_length=50, verbose_name='Sobrenome')),
                ('nome_guerra', models.CharField(max_length=30, verbose_name='Nome de Guerra')),
                ('data_de_aniversario', models.DateField(verbose_name='Data de Aniversário')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='E-mail')),
            ],
        ),
        migrations.CreateModel(
            name='PostoGraduacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('posto_graduacao', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='UsuarioPersonalizado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('primeiro_nome', models.CharField(max_length=30)),
                ('sobrenome', models.CharField(max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Escore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('escore', models.DecimalField(decimal_places=2, max_digits=5)),
                ('data_do_registro', models.DateField(auto_now_add=True)),
                ('disciplina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.disciplina')),
                ('estudante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.estudante')),
            ],
        ),
        migrations.CreateModel(
            name='Inscricao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_de_inscricao', models.DateField(auto_now_add=True, verbose_name='Data de Inscrição')),
                ('disciplina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.disciplina')),
                ('estudante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.estudante')),
            ],
        ),
        migrations.CreateModel(
            name='Monitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricula', models.CharField(max_length=10, unique=True, verbose_name='Matrícula')),
                ('primeiro_nome', models.CharField(max_length=30, verbose_name='Primeiro Nome')),
                ('sobrenome', models.CharField(max_length=50, verbose_name='Sobrenome')),
                ('nome_guerra', models.CharField(max_length=30, verbose_name='Nome de Guerra')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='E-mail')),
                ('disciplina', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.disciplina')),
                ('posto_graduacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.postograduacao')),
            ],
        ),
        migrations.CreateModel(
            name='Instrutor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricula', models.CharField(max_length=10, unique=True, verbose_name='Matrícula')),
                ('primeiro_nome', models.CharField(max_length=30, verbose_name='Primeiro Nome')),
                ('sobrenome', models.CharField(max_length=50, verbose_name='Sobrenome')),
                ('nome_guerra', models.CharField(max_length=30, verbose_name='Nome de Guerra')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='E-mail')),
                ('disciplina', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.disciplina')),
                ('posto_graduacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.postograduacao')),
            ],
        ),
        migrations.AddField(
            model_name='estudante',
            name='posto_graduacao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.postograduacao'),
        ),
        migrations.CreateModel(
            name='Presenca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('status', models.CharField(choices=[('Presente', 'Presente'), ('Ausente', 'Ausente')], max_length=10)),
                ('estudante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.estudante')),
            ],
        ),
    ]
