# Generated by Django 5.2 on 2025-04-29 23:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inscricao',
            old_name='data_inscricao',
            new_name='data_de_inscricao',
        ),
    ]
