# Generated by Django 5.2 on 2025-05-03 12:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rename_data_inscricao_inscricao_data_de_inscricao'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostoGraduacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('posto_graduacao', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='estudante',
            name='posto_graduacao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.postograduacao'),
        ),
        migrations.AlterField(
            model_name='instrutor',
            name='posto_graduacao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.postograduacao'),
        ),
        migrations.AlterField(
            model_name='monitor',
            name='posto_graduacao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.postograduacao'),
        ),
    ]
